FROM ubuntu:18.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install python3.6-minimal python3-distutils gawk sed jq tar unzip git curl wget redir socat traceroute net-tools iputils-ping mtr-tiny haproxy rsync && \
    curl -o get-pip.py https://bootstrap.pypa.io/pip/3.6/get-pip.py && python3.6 get-pip.py && rm get-pip.py && \
    pip --no-cache-dir install awscli httpie yq
