FROM alpine:3.6

RUN apk add --no-cache bash coreutils findutils diffutils grep \
    python gawk sed jq tar unzip git curl wget socat iputils haproxy rsync && \
    curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py && python get-pip.py && rm get-pip.py && \
    pip --no-cache-dir install awscli httpie yq

