FROM ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install python3.10-minimal python3-distutils gawk sed jq tar unzip git curl wget redir socat traceroute net-tools iputils-ping mtr-tiny haproxy rsync && \
    curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py && python3.10 get-pip.py && rm get-pip.py && \
    pip --no-cache-dir install awscli httpie yq
