FROM ubuntu:26.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install python3.14-minimal gawk sed jq tar unzip git curl wget redir socat traceroute net-tools iproute2 iputils-ping mtr-tiny haproxy rsync httpie
