FROM alpine:3.15

RUN apk add --no-cache bash coreutils findutils diffutils grep \
    python3 gawk sed jq tar unzip git curl wget socat iputils net-tools haproxy rsync && \
    curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm get-pip.py && \
    pip --no-cache-dir install awscli httpie yq
