FROM ubuntu:24.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install python3.12-minimal gawk sed jq tar unzip git curl wget redir socat traceroute net-tools iproute2 iputils-ping mtr-tiny haproxy rsync && \
    curl -o get-pip.py https://bootstrap.pypa.io/get-pip.py && python3.12 get-pip.py --break-system-packages && rm get-pip.py && \
    pip --no-cache-dir install awscli httpie yq
