name: build-image-and-push

on:
  push:
    branches: master
    paths:
      - 'Dockerfile*'
      - '.github/workflows/**'
  schedule:
    - cron: '21 3 * * 0' # weekly build

jobs:
  buildx:
    # matrix magic
    strategy:
      matrix:
        target: [ubuntu2404, ubuntu2204, alpine]
      fail-fast: false
    # end matrix magic
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push (${{ matrix.target }})
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.${{ matrix.target }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/riscv64
          push: true
          tags: |
            dictcp/utils:${{ matrix.target }},ghcr.io/dictcp/utils:${{ matrix.target }}
            ${{ matrix.target == 'ubuntu2404' && 'dictcp/utils:latest,ghcr.io/dictcp/utils:latest,dictcp/utils:ubuntu,ghcr.io/dictcp/utils:ubuntu' || '' }}
