name: docker-utils

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx (alpine)
        run: |
          docker buildx build \
            -f Dockerfile.alpine . \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            -t dictcp/utils:alpine \
            --push
      -
        name: Run Buildx (ubuntu)
        run: |
          docker buildx build \
            -f Dockerfile.ubuntu . \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            -t dictcp/utils:ubuntu \
            --push

